version: "3"
services:
  node-bootstrap:
    image: aceberg/node-bootstrap
    restart: unless-stopped
    ports:
    - 8850:8850
  wyl:
    image: aceberg/watchyourlan
    network_mode: "host"      
    restart: unless-stopped
    command: "-n http://YOUR_IP:8850"   # put your server IP or DNS name here
    depends_on:
      - node-bootstrap
    volumes:
    - ~/.dockerdata/wyl:/data
    environment:
      TZ: Asia/Novosibirsk              # required: needs your TZ for correct time
      IFACE: "enp4s0"                   # required: 1 or more interface
      DBPATH: "/data/db.sqlite"         # optional, default: /data/db.sqlite
      GUIIP: "0.0.0.0"                  # optional, default: localhost
      GUIPORT: "8840"                   # optional, default: 8840
      TIMEOUT: "120"                    # optional, time in seconds, default: 60
      SHOUTRRR_URL: ""                  # optional, set url to notify
      THEME: "darkly"                   # optional
      IGNOREIP: "no"                    # optional