name: Dev-to-docker

on:
  workflow_dispatch:

env:
  IMAGE_NAME: watchyourlan
  TAGS: dev


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Push Docker Image to docker.io
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}